---
output: pdf_document
---

# Discussion
## Other Potential Models for Molecular Dynamics Study
### Morse interaction model

Morse Interaction model is described as a combination of Brownian motion and improved OU process.
Under this model, $X_{t}$ is a Markov process satisfying the stochastic differential equation (SDE):
$$
dX_{t}=-U'(X_{t})dt+\sigma dB_{t}
$$

And $U'(x)$ is the derivative of the Morse potetial energy function: 
$$
U'(x)=\gamma \centerdot(1-e^{-\alpha \centerdot (x-u)})
$$
The distance $X_{t}$ is set to be strictly positive, $X_{t}$ > 0. When $X_{t}$ is too large, repulsive forces allow bond breaking to occur - the molecules again resemble brownian motion. 
When the donor and acceptor again get close to each other, the bond is reformed and exchange of photons takes place. The dynamics then resembles OU process.

Morse interaction model is a comprehensive approach towards dynamics study of molecular interaction. 

S.Schelstraete, H. Verschelde (1999). Molecular Dynamics. Retrieved from https://www.sciencedirect.com/topics/chemistry/morse-potential
  
### Lennard-Jones Potential
The interaction between two non-bonded and un-charged atoms, known as Van der Waals interaction, has been expressed in terms of potential energy. Lennard-Jones potential is probably the most famous pair potential descriping interatomic Van der Waals forces. It consists of two parts:  
1) A steep repulsive term; and  
2) A smooth attractive term

$$
V(r)=4\epsilon [\left(\frac{\sigma}{r}\right)^{12}-\left(\frac{\sigma}{r}\right)^{6}]
$$  
In particular, $V(x)$ is the intermolecular potential between the two molecules, and $r$ is the distance of separation between both molecules.  

Apart from being a widely used model itself, Lennard-Jones potential also sometimes forms one of 'building blocks' of many force fields, due to its computational expediency. 

However, Lennard-Jones potential is not designated to model donor-acceptor interactions.

  

Libretexts. (2019, June 5). Lennard-Jones Potential. Retrieved from https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Physical_Properties_of_Matter/Atomic_and_Molecular_Properties/Intermolecular_Forces/Specific_Interactions/Lennard-Jones_Potential


