---
output: pdf_document
---

# Discussion
## Other Potential Models for Molecular Dynamics Study
### Morse interaction model

Morse Interaction model is described as a combination of Brownian motion and improved OU process.
Under this model, $X_{t}$ is a Markov process satisfying the stochastic differential equation (SDE):
$$
dX_{t}=-U'(X_{t})dt+\sigma dB_{t}
$$

And $U'(x)$ is the derivative of the Morse potetial energy function: 
$$
U'(x)=\gamma \centerdot(1-e^{-\alpha \centerdot (x-u)})
$$
The distance $X_{t}$ is set to be strictly positive, $X_{t}$ > 0. When $X_{t}$ is too large, repulsive forces allow bond breaking to occur - the molecules again resemble brownian motion. 
When the donor and acceptor again get close to each other, the bond is reformed and exchange of photons takes place. The dynamics then resembles OU process.

Morse interaction model is a comprehensive approach towards dynamics study of molecular interaction. 

S.Schelstraete, H. Verschelde (1999). Molecular Dynamics. Retrieved from https://www.sciencedirect.com/topics/chemistry/morse-potential
  
### Lennard-Jones Potential
The interaction between two non-bonded and un-charged atoms, known as Van der Waals interaction, has been expressed in terms of potential energy. Lennard-Jones potential is probably the most famous pair potential descriping interatomic Van der Waals forces. It consists of two parts:  
1) A steep repulsive term; and  
2) A smooth attractive term

$$
V(r)=4\epsilon [\left(\frac{\sigma}{r}\right)^{12}-\left(\frac{\sigma}{r}\right)^{6}]
$$  
In particular, $V(x)$ is the intermolecular potential between the two molecules, and $r$ is the distance of separation between both molecules.  

Apart from being a widely used model itself, Lennard-Jones potential also sometimes forms one of 'building blocks' of many force fields, due to its computational expediency. 

However, Lennard-Jones potential is not designated to model donor-acceptor interactions.

  

Libretexts. (2019, June 5). Lennard-Jones Potential. Retrieved from https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Physical_Properties_of_Matter/Atomic_and_Molecular_Properties/Intermolecular_Forces/Specific_Interactions/Lennard-Jones_Potential

## Research Direction 2
For experiments simulated from OU, we can see a constant improvement in picking the correct model when $\gamma$ goes up. As $\gamma\rightarrow 0$, $\omega_{\Delta{t}}\rightarrow 1$ and $\tau$ is still a constant, (todo: equation) becomes $X_{t+\Delta{t}}|X_t \sim N(X_t, 0)$,which is in the same form as (todo:equation). Thus, it is difficult to distinguish the OU simulation from the BM model. As $\gamma$ goes up, $\omega_{\Delta{t}}\rightarrow 0$, two model equations differ in mean and variance, and hence becomes easier to distinguish.

For experiments simulated from BM, we can see a general improvement in picking the correct model when $\sigma_{BM}$ goes up, however, the improvement stops at $\sigma_{BM}=3$ for most of the experiments. We analyze in the following two aspects. First of all, when $\sigma_{BM} \rightarrow 0$, (todo:equation) becomes $X_{t+\Delta{t}}|X_t \sim N(X_t, 0)$. From the discussion in the previous paragraph, when $\gamma \rightarrow 0$, (todo:equation) also becomes $X_{t+\Delta{t}}|X_t \sim N(X_t, 0)$. Thus, if we do parameter inferences relatively well, it will be difficult to tell apart two models. Furthermore, when $\sigma$ becomes too large with respect to $\beta_0$ and $\beta_1$, for example, when $\sigma=3$ with respect to $\beta_0=5$ and $\beta_1=1$, the probability of $X_t$ being large becomes higher. In this case, $exp(\beta_0 -\beta_1 X_t)$ becomes close to 0, and the generated $Y_t$ from Poission (todo:equation) is more likely to be 0. Consequently, $Y_t$ does not provide enough information to the underlying generated process, and hence difficult to tell apart BM model from OU model.

Another observation to note is that as a general rule, $|\beta_0-\beta_1|$ cannot be too large, otherwise, many NAs from (todo:equation) will be generated because R cannot handle values $ > e^{22}$ (todo:checkthisvalue). Repetively generating values until no NAs results in the enter process being slow.

## Potential improvements in implementation
### Other model selection criterion 
We can consider other model selection criteria for research direction 2. For example, AIC and Mallow CP. Using a weighted of different criteria for model selection makes the result less biased. 

### Random start for BM model
As discussed in the methodology section, random. We figured out how to implement random start for OU model by reparameterization. Consequently, the accuracy of OU inferences has improved sigfinicantly.

