---
title: "Introduction_OU"
author: "Yi Xiang"
date: "12/04/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction:

## Dynamical Analysis of Molecular Interactions:  

### Brownian Motion  
Brownian motion is widely used to model the donor-acceptor distance during free diffusion in the molecular environment.The random flow of molecular motion is subtained by collision of moving molecules. In our dynamical analysis, $X_{t}$ is denoted as the donar-acceptor distance at time t. It is a Gaussian Markov process with the following transition density:

\begin{equation} \label{eq:1} X_{t+\Delta t}|X_{t} \sim N(X_{t}, \sigma^2 \Delta t) \end{equation}  

Every subsequent variation in distance by an increment of $\Delta t$ has a mean-reverting nature. That is, the donor-acceptor distance in the next instance revolves around the mean of the process in any direction. In the Brownian Motion model, the mean is set as the current-time donor-aceptor distance. With the process involving Markov element, the sequence of possible molecular motions is only current-state dependent, and it is often refered to as memoryless. The collection of the independent processes at each instance $\Delta t$, are recognised as jointly Gaussian (normal).  

The variation is determined by the diffussion rate $\sigma$, multiplied by $\Delta t$. The diffussion rate is set constant in our study, which implies the thermal temperature and pressure are kept unchanged and no external force is applied into the system.  

However, the many-body interactions that yield the random pattern cannot be solved by Brownian model that accounts every involved molecule. Therefore, the brownian itself is not capable to model the full motion of molecules especially during the photon exchange between donor and acceptor. This is ultimately a downside of Brownian model in our dynamical analysis. 

### Ornstein-Uhlenbeck Process 
Ornstein-Uhlenbeck process is further developed from Brownian motion by L. S. Ornstein and G. E. Uhlenbeck.[1]
The Ornstein-Uhlenbeck process is a stochastic Gaussian process with continuous paths. The Ornstein-Uhlenbeck process is defined as the following stochastic differential equation: 
\begin{equation} \label{eq:2} dX_t = \gamma (\mu - X_t) dt + \sigma dW_t \end{equation} 
Where $W_t$ is a standard Brownian motion on $t \in (0, \infty),\gamma > 0, \sigma > 0$
$X_t$ is a stationary Gaussian Markov process with transition density: 
\begin{equation} \label{eq:3} X_{t+\Delta t}|X_{t} \sim N(\mu + \omega_{\Delta t} (X_{t} - \mu), \tau^2(1- \omega_{\Delta t}^2)) \end{equation} 
where $\omega_{\Delta t} = exp(-\gamma \Delta t)$ and $\tau^2 = \sigma^2/(2 \gamma)$.
Compared to Brownian motion model, the Ornstein-Uhlenbeck process includes more factors from the environment that can impact the change of the distance. The Ornstein-Uhlenbeck process has four components to describe the molecule interactions which are $\gamma$, $\mu$, $\sigma$, and $dW_t$.The interpretation of $\gamma$ is the rate of mean reversion. The Ornstein-Uhlenbeck process shares mean reversion nature with Brownian motion. This property allows that the distance will eventually revert to the long-run average.The rate indicates how strong the distance will react toward the attractor. $\mu$ is the asymptotic mean of "bond" length. $\sigma$ is the parameter showing the volatility of noise. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4898467/). The Ornstein-Uhlenbeck process represents how molecule move towards the attractors $\mu$ with Brownian motion. 

The Ornstein-Uhlenbeck process considers the current state and the speed of molecule interaction, which is preferred when modeling the many-body interactions.Since with different type of donor-acceptor interactions, the molecule will react differently. 
One of the downsides of Ornstein-Uhlenbeck process is that a very small amount of variation such as measurement error can profoundly affect the performance of the model. Also the distance is always positive. However, the donor acceptor in Ornstein-Uhlenbeck allows negative distance. 



### Drawbacks of Using R 

# Reference 
[1]. G. E. Uhlenbeck and L. S. Ornstein, On the theory of Brownian
motion, Physical Review 36 (1930), 823–841.