---
output:
  pdf_document: default
  html_document: default
---
# Introduction:

## Dynamical Analysis of Molecular Interactions:  

### Brownian Motion  
Brownian motion is widely used to model the donor-acceptor distance during free diffusion in the molecular environment.The random flow of molecular motion is subtained by collision of moving molecules. In our dynamical analysis, $X_{t}$ is denoted as the donar-acceptor distance at time t. It is a Gaussian Markov process with the following transition density:

$$ X_{t+\Delta t}|X_{t} = N(X_{t}, \sigma^2 \Delta t)$$  

Every subsequent variation in distance by an increment of $\Delta t$ has a mean-reverting nature. The donor-acceptor distance in the next instance revolves around the mean of the process in any direction, that is set as the current-time donor-aceptor distance. With the process involving Markov element, the sequence of possible molecular motions is only current-state dependent, and it is often refered to as memoryless. The collection of the independent processes at each instance $\Delta t$, are recognised as jointly Gaussian (normal).  

The variation is determined by the diffussion rate $\sigma$, multiplied by $\Delta t$. The diffussion rate is set constant in our study, which implies the thermal temperature and pressure are kept unchanged and no external force is applied into the system.  

However, the many-body interactions that yield the random pattern cannot be solved by Brownian model that accounts every involved molecule. Therefore, the brownian itself is not capable to model the full motion of molecules especially during the photon exchange between donor and acceptor. This is ultimately a downside of Brownian model in our dynamical analysis. 
